# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lolpath', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ_id', models.IntegerField(verbose_name='Riot champ ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='MatchReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane', models.CharField(max_length=32, verbose_name='Lane')),
                ('win', models.BooleanField(default=False)),
                ('kills', models.IntegerField(verbose_name='Kills')),
                ('deaths', models.IntegerField(verbose_name='Deaths')),
                ('assists', models.IntegerField(verbose_name='Assists')),
                ('datetime', models.DateTimeField(verbose_name='Match date')),
                ('ranked', models.BooleanField(verbose_name='Ranked game')),
                ('gold', models.IntegerField(verbose_name='Gold earned')),
                ('level', models.IntegerField(verbose_name='Level reached')),
                ('cs', models.IntegerField(verbose_name='Creep score')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('game_type', models.CharField(default='Normal', max_length=64, verbose_name='Game type')),
                ('season', models.CharField(max_length=64, verbose_name='Season')),
                ('server_id', models.CharField(default='la1', max_length=32, verbose_name='Server')),
                ('champion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lolpath.Champion')),
            ],
        ),
        migrations.RenameField(
            model_name='summoner',
            old_name='level',
            new_name='summoner_level',
        ),
        migrations.AddField(
            model_name='summoner',
            name='account_id',
            field=models.IntegerField(default=False, verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='summoner',
            name='profile_icon_id',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summoner',
            name='summoner_id',
            field=models.IntegerField(default=False, verbose_name='Id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchreg',
            name='summoner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lolpath.Summoner'),
        ),
    ]
