# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolpath', '0002_auto_20170614_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='champ_id',
        ),
        migrations.AlterField(
            model_name='champion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
