# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lolpath', '0004_auto_20170614_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summoner',
            old_name='lolpath_user_id',
            new_name='lolpath_user',
        ),
    ]
