# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolpath', '0006_summoner_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='lane',
            field=models.CharField(default=False, max_length=64),
            preserve_default=False,
        ),
    ]
