# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lolpath', '0007_summoner_lane'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchreg',
            old_name='server_id',
            new_name='server',
        ),
        migrations.RemoveField(
            model_name='matchreg',
            name='season',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='lane',
        ),
        migrations.AddField(
            model_name='champion',
            name='lane',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchreg',
            name='match_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Match date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchreg',
            name='datetime',
            field=models.DateTimeField(verbose_name='Dont use'),
        ),
    ]
