# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lolpath', '0008_auto_20170615_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchreg',
            name='datetime',
        ),
    ]
