# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolpath', '0010_auto_20170615_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchreg',
            name='gold',
            field=models.FloatField(verbose_name='Gold earned'),
        ),
    ]
